[package]
name = "aera"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
# inkwell = { version = "0.6.0", features = ["llvm17-0"] }
thiserror = "2.0.12"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.0"